# Generated by Django 4.0.5 on 2022-09-30 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_customuser_is_superuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('change_name', 'can change name of product'),)},
        ),
    ]
